INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (1, 'f', 'Lập trình hướng đối tượng là phương pháp mới của lập trình máy tính, chia chương trình thành các hàm; quan tâm đến chức năng của hệ thống.', 1);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (2, 't', 'Lập trình hướng đối tượng là phương pháp đặt trọng tâm vào các đối tượng, nó không cho phép dữ liệu chuyển động một cách tự do trong hệ thống; dữ liệu được gắn với các hàm thành phần.', 1);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (3, 'f', 'Lập trình hướng đối tượng là phương pháp đặt trọng tâm vào các chức năng, cấu trúc chương trình được xây dựng theo cách tiếp cận hướng chức năng.', 1);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (4, 'f', 'Lập trình hướng đối tượng là phương pháp lập trình cơ bản gần với mã máy.', 1);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (5, 'f', 'Tính đóng gói, tính trừu tượng.', 2);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (6, 't', 'Tính đóng gói, tính kế thừa, tính đa hình, tính trừu tượng.', 2);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (7, 'f', 'Tính chia nhỏ, tính kế thừa.', 2);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (8, 'f', 'Tính đóng gói, tính kế thừa, tính đa hình, tính đặc biệt hóa.', 2);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (9, 'f', 'Object Open Programming.', 3);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (10, 'f', 'Object Oriented Proccessing.', 3);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (12, 'f', 'Open Object Programming', 3);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (11, 't', 'Object Oriented Programming.', 3);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (13, 'f', 'Ngôn ngữ lập trình pascal, C, C++ là ngôn ngữ lập trình cấu trúc.', 4);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (14, 'f', 'Ngôn ngữ lập trình C++, Java là ngôn ngữ lập trình cấu trúc.', 4);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (15, 'f', 'Ngôn ngữ lập trình C, C++ là ngôn ngữ lập trình hướng đối tượng.', 4);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (16, 't', 'Ngôn ngữ lập trình pascal, C là ngôn ngữ lập trình cấu trúc.', 4);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (17, 'f', 'C, Pascal là ngôn ngữ lập trình cấu trúc.', 5);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (18, 'f', 'C++ là ngôn ngữ lập trình cấu trúc.', 5);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (19, 't', 'Ngôn ngữ Pascal  là ngôn ngữ lập trình hướng đối tượng.', 5);
INSERT INTO "options"("id", "correct", "option_content", "question_id") VALUES (20, 'f', 'Ngôn ngữ C++, Java là ngôn ngữ lập trình hướng đối tượng.', 5);
