INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214201, 'Nhập môn tin học', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214321, 'Lập trình cơ bản', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214331, 'Lập trình nâng cao', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214231, 'Cấu trúc máy tính', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214241, 'Mạng máy tính căn bản', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214441, 'Cấu trúc dữ liệu', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214242, 'Nhập môn hệ điều hành', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214251, 'Hệ điều hành nâng cao', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214351, 'Lý thuyết đồ thị', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214442, 'Nhập môn cơ sở dữ liệu', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214352, 'Thiết kế hướng đối tượng', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214462, 'Lập trình web', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214461, 'Lập trình mạng', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214370, 'Nhập môn công nghệ phần mềm', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214471, 'Hệ thống thông tin quản lý', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214282, 'Mạng máy tính nâng cao', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214451, 'Hệ quản trị cơ sở dữ liệu', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214273, 'Lập trình mạng nâng cao', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214372, 'Lập trình .NET', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214463, 'Nhập môn trí tuệ nhân tạo', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214485, 'Data Mining', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214477, 'Data Warehouse', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214383, 'Quản lý dự án phần mềm', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214488, 'Chuyên đề Oracle', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214284, 'Lập trình C++ trên Linux', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214271, 'Quản trị mạng', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214286, 'Chuyên đề Java', 1, 0);
INSERT INTO "subjects"("id", "course_name", "status", "is_deleted") VALUES (214374, 'Chuyên đề Web', 1, 0);
